pipeline:
  build-docker-images:
    displayName: Build Docker Images
    image: docker:latest
    services:
      - docker:dind
    commands:
      - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD ghcr.io
      - docker build -t ghcr.io/$DOCKER_USER/my_nas:latest .
      - docker push ghcr.io/$DOCKER_USER/my_nas:latest
      - docker build -t ghcr.io/$DOCKER_USER/my_nas:quarkdrive ./quarkdrive
      - docker push ghcr.io/$DOCKER_USER/my_nas:quarkdrive
